spring.application.name=ODAS

spring.datasource.url=jdbc:h2:./data/database/db;INIT=CREATE SCHEMA IF NOT EXISTS a
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.schema-locations=file:data/scripts/init_schema.sql
#spring.sql.init.data-locations=file:data/scripts/init_data.sql

#spring.web.error.whitelabel.enabled=false